
[tool.pyflow]
name = "."
py_version = "3.9"
version = "0.1.0"
authors = ["DESKTOP-E8K7NFN\Noel Khan <noel5khan@gmail.com>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]

